# Generated by Django 3.2 on 2022-01-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ('variation_category',)},
        ),
    ]
