# Generated by Django 3.2 on 2022-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220324_1116'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='order_order_order_n_fb1851_idx'),
        ),
    ]
